const interestOptions = [
  'Science',
  'Math',
  'Computer Science',
  'English/Language Arts',
  'Finance',
  'Economics',
  'History',
  'Engineering',
  'Machine Learning',
  'Web Development',
  'Physics',
  'Chemistry',
  'Football',
  'Basketball',
  'Baseball',
  'Tennis',
  'Soccer',
  'Hockey',
  'Volleyball',
  'Track',
  'Cross Country',
  'Golf',
  'Arts',
  'Film',
  'Video Production',
];

export default interestOptions;
